[options]
addons_path = /mnt/extra-addons,
              /mnt/openg2p-registry,
              /mnt/openg2p-social-registry,
              /mnt/openg2p-community-addons,
              /mnt/openg2p-ati,
              /usr/lib/python3/dist-packages/odoo/addons

db_host = db
db_port = 5432
db_name = odoo
db_user = odoo

http_port = 8069
longpolling_port = 8072

log_level = info
logfile   = /var/log/odoo/odoo.log